image: ruby:2.4

variables:
  JEKYLL_ENV: production
  LC_ALL: C.UTF-8
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - bundle install

pages:
  stage: deploy
  script:
  - rake build
  artifacts:
    paths:
    - public
  only:
  - master
