# General
name: StaticPage
title: Welcome to StaticPage!
description: Create your own Coming Soon, Under Maintenance, and 404 pages.
author: Idan Goldman.
email: root@staticpage.io
logo: /assets/images/logo.svg

# Collections
collections:
  posts:
    permalink: /blog123/:title
    layout: post

# Permalinks
url: 'https://staticpage.io'
baseurl: ''
host: staticpage.web
port: 1234

# Build settings
# theme: minima
source: ./source
destination: ./public
exclude:
  - 'assets/images/favicon'
  - 'assets/images/illustrations'
timezone: Asia/Jerusalem
markdown: kramdown

# Plugins
plugins:
  - jekyll-analytics
  - jekyll-default-layout
  - jekyll-favicon
  - jekyll-feed
  - jekyll-inline-svg
  - jekyll-last-modified-at
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-tidy

# SASS
sass:
  style: compressed
  load_paths:
    - ../kit

# HTML Compression
jekyll_tidy:
  compress_html: true

# Favicon
favicon:
  source: assets/images/favicon.png
  path: assets/images/favicon
  safari-pinned-tab:
    mask-icon-color: '#2ea52c'
  ie:
    tile-color: '#2ea52c'

# SVG
svg:
  optimize: true
