# General
name: StaticPage
title: Welcome to StaticPage!
description: Create your own Coming Soon, Under Maintenance, and 404 pages.
author: Idan Goldman, chief of stuff.
email: root@staticpage.io
url: "https://staticpage.io"
baseurl: ""

# Build settings
source: ./source
destination: ./public
exclude: ['images/favicon']
timezone: Asia/Jerusalem
markdown: kramdown
host: staticpage.web
port: 1234

# theme: minima
plugins:
  - jekyll-analytics
  - jekyll-default-layout
  - jekyll-favicon
  - jekyll-feed
  - jekyll-paginate-v2
  # - jekyll-picture-tag
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap

favicon:
  source: images/favicon.svg
  path: /images/favicon
  safari-pinned-tab:
    mask-icon-color: "#2ea52c"
  ie:
    tile-color: "#2ea52c"
